### ISSUE TITLE
Trouble reading table in specification

### ISSUE THREAD

**Issue by gzagatti** [nvim-neorg/norg-specs#1]
I am having a hard time reading the following section of the [specification](https://github.com/nvim-neorg/norg-specs/blob/main/0.1-specification.norg). 

Is this a table markup? Also, it feels like there is `::` missing at the top to preserve symmetry with the rest. Any help would be appreciated.

```norg

  The following list outlines all valid *detached modifiers*. The list also adds various possible
  properties to each category which will be explained in more detail below.
  : . : Character
  : > : Name
  : > : Categories
  : _ : `*`
  : > : Headings
  :: >
     - Structural
     - Nestable
  ::
  : _ : `-`
  : > : Unordered Lists
  :: >
     - Nestable
  ::
  : _ : `~`
  : > : Ordered Lists
  :: >
     - Nestable
  ::
  : _ : `>`
  : > : Quotes
  :: >
     - Nestable
  ::
  : _ : `$`
  : > : Definitions
  :: >
     - Range-able
  ::
  : _ : `^`
  : > : Footnotes
  :: >
     - Range-able
  ::
  : _ : `&`
  : > : Variables
  :: >
     - Range-able
     - Logical
  ::
  : _ : `:`
  : > : Table cells
  :: >
     - Range-able
  ::
  : _ : `%`
  : > : Attributes
  :: >
     - Range-able
     - Logical
  ::
  : _ : `=`
  : > : Macros
  :: >
     - Range-able
     - Logical
  ::
```

**Comment by gzagatti** [comment]
Thanks for clarifying. 

I got quite confused distinguishing table cell definition that spans multiple lines

```norg
:: A2
Foo bar
::
```

The `:` intersecting modifier character and the indent segment extension:

```norg
- ::
This is some content
---
```

Perhaps if table cell modifier could use a different character it would be easier to read.

**Comment by gzagatti** [comment]
If you are still considering changes to the specification. I would consider using `|` for table cells and another markup for Standard Ranged Tags like `?` or the lozenge from Pollen `◊`.

It would be easier on the eyes, as an illustration:

```norg
| . : Character
| > : Name
| > : Categories
| _ : `*`
| > : Headings
|| >
   - Structural
   - Nestable
||
| _ : `-`
| > : Unordered Lists
|| >
   - Nestable
||
| _ : `~`
| > : Ordered Lists
|| >
   - Nestable
||
| _ : `>`
| > : Quotes
|| >
   - Nestable
||
| _ : `$`
| > : Definitions
|| >
   - Range-able
||
| _ : `^`
| > : Footnotes
|| >
   - Range-able
||
| _ : `&`
| > : Variables
|| >
   - Range-able
   - Logical
||
| _ : `:`
| > : Table cells
|| >
   - Range-able
||
| _ : `%`
| > : Attributes
|| >
   - Range-able
   - Logical
||
| _ : `=`
| > : Macros
|| >
   - Range-able
   - Logical
||
```

**Comment by max397574** [comment]
I think they aren't really considering changes to the specs.

**Comment by mrossinek** [comment]
Thank you for the suggestion @gzagatti! It is not like we are against any further spec changes, but at this point they would need to be very well motivated. We have a put **a lot** of discussion and thought into the current spec and while I see your point, the final choice of characters to use comes somewhat down to personal taste. And both, @vhyrro and I, agree that we prefer the `:` over the `|` char for the table spec, especially since in combination with the intersection modifier ` : ` (which we actually came up with while designing the table syntax) it pairs (in our opinion) very well.
On top of that, the `|` char is already being used for standard (i.e. non-verbatim ranged tags) which (while not ruling it out here) does not go very well together in our opinion.

All that said, thank you very much for taking such a detailed look at this spec and taking the time to provide this feedback! It really is much appreciated!

**Comment by gzagatti** [comment]
You're welcome!
