### ISSUE TITLE
Ordered lists number support

### ISSUE THREAD

**Issue by theherk** [nvim-neorg/norg-specs#19]
Any plans to support numbers representing ordered lists? There are other subtle changes that aren't clear like `[ ]` and `[x]` becoming `( )` and `(x)`, but those don't diminish anything. But ordered lists without being identified by an ordered set like integers or alpha, seems to imply the file is not meant to be readable without rendering.

> This list type is only useful for data that needs to be kept in sequence. In contrast to other formats which may use a syntax like `1.`/`1)`, Norg counts the items automatically - this reduces complexity and makes reordering items simple.

I understand there is a small amount of simplicity gained in not requiring a recount function, but that doesn't seem worth having a file type be non-human readable.

Forgive me. Very cool and interesting project, but I think this would be an improvement.

**Comment by vhyrro** [comment]
I understand the reason why numbers are considered very important to many. It's definitely a more human approach, similarly to whitespace for indentation of list items.

Norg has many goals in mind, and these include removing common pitfalls and maintaining syntax and parsing consistency. Norg should be a file format that strikes as close of a balance between machine readable and human readable as possible. Think of it as the Rust of markup languages - it's nice to write once you drop your notion of other languages and acknowledge some of the initial friction.

Number-based ordered lists are simply too tricky to support without creating major exceptions. I'll try to list them all out below.

## Detached Modifiers

Norg works on generalizations, i.e. - all tags (`#`, `|`, `@`, `+`, `=`) are from a single syntax set called "macros". In the case of headings, lists, quotes etc. these belong to the **detached modifier** family.
The family is very distinguishable in that all elements that belong to it start at the beginning of a line, consist of one (or many) of the *same punctuation character*, and are immediately followed by whitespace. They are then followed by either a single line of text, a paragraph, or any amount of items until a termination character is reached (this behaviour is governed by more specific generalizations which we call categories of detached modifiers).

Note a very specific detail. All detached modifiers in norg (headings, quotes, lists, unordered lists, footnotes, definition lists) use *punctuation characters* to distinguish them from the alphanumeric characters that make up simple paragraphs. The most basic problem with ordered lists is that they break two rules - they use alphanumeric characters (`A.`, `1)`) and they consist of completely different characters that may be mixed and matched, take for instance `A.`/`1.`/`I.` or `A)`/`1)`/`I)`.

Not only that, list items may be continually nested by repeating the same character. `-- Hello` creates a level 2 list item. To support this with ordered lists, you would also have to allow for the repetition of characters to create nesting. So is `11.` the eleventh list element or a nested first element? `1..` is also really pushing it.

Mixing alphanumeric characters additionally creates other sorts of rare but annoying issues for those who encounter them. A simple example is:
```
And when I asked for the meaning of life, their response was
42. I was shocked.
```
A forty-second list item in the middle of my paragraph? What's that doing there.
Markdown resolves the 'ambiguity' by requiring that lists start at `1.`, but that's creating *yet* another syntactical edge case for a parser. That's a double whammy already!

## And Then There's The Semantic Issues...

Syntax aside, there are semantic pitfalls. Reordering is a tedious process left to the user. A semantic interpreter ignores the numbers you write too; this:
```
1. Hello
4. Hello
10. Hello
```
is seen by any semantic interpreter as:
```
1. Hello
2. Hello
3. Hello
```
This means that the only reason this feature exists is for the human's eyes. The numbers themselves don't hold a single bit of weight to them for anything actually interpreting the text.

---

As for the `( )` instead of `[ ]`, those aren't random choices either. They disambiguate anchors, which are written `[like this]`.

Hope this long reply gives you some insight! If you have other questions then do ask :)

**Comment by theherk** [comment]
This is such a great explanation. I forgot to come back and say as much until now, weeding through my notifications, but yeah... awesome.
